# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_landmark_cal.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'model_landmark_cal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18model_landmark_cal.proto\x12\x1aModel_Landmark2_calculator\":\n\x19Model_Landmark2_Input_img\x12\x1d\n\x15model_landmark2_idata\x18\x01 \x01(\x0c\";\n\x1aModel_Landmark2_Output_img\x12\x1d\n\x15model_landmark2_odata\x18\x01 \x01(\t2\x99\x01\n\x1aModel_Landmark2_Calculator\x12{\n\nAdd_second\x12\x35.Model_Landmark2_calculator.Model_Landmark2_Input_img\x1a\x36.Model_Landmark2_calculator.Model_Landmark2_Output_imgb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_landmark_cal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODEL_LANDMARK2_INPUT_IMG']._serialized_start=56
  _globals['_MODEL_LANDMARK2_INPUT_IMG']._serialized_end=114
  _globals['_MODEL_LANDMARK2_OUTPUT_IMG']._serialized_start=116
  _globals['_MODEL_LANDMARK2_OUTPUT_IMG']._serialized_end=175
  _globals['_MODEL_LANDMARK2_CALCULATOR']._serialized_start=178
  _globals['_MODEL_LANDMARK2_CALCULATOR']._serialized_end=331
# @@protoc_insertion_point(module_scope)
