import sys, os
script_directory = os.path.dirname(os.path.abspath(__file__))
wanted_dir='/'
for i in range(1,len(script_directory.split('/'))-1):
    wanted_dir += script_directory.split('/')[i]+'/'
sys.path.append(wanted_dir)
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from model_1 import model_landmark_cal_pb22 as model__landmark__cal__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in model_landmark_cal_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class Model_Landmark2_CalculatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Add_second = channel.unary_unary(
                '/Model_Landmark2_calculator.Model_Landmark2_Calculator/Add_second',
                request_serializer=model__landmark__cal__pb2.Model_Landmark2_Input_img.SerializeToString,
                response_deserializer=model__landmark__cal__pb2.Model_Landmark2_Output_img.FromString,
                _registered_method=True)


class Model_Landmark2_CalculatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Add_second(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Model_Landmark2_CalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Add_second': grpc.unary_unary_rpc_method_handler(
                    servicer.Add_second,
                    request_deserializer=model__landmark__cal__pb2.Model_Landmark2_Input_img.FromString,
                    response_serializer=model__landmark__cal__pb2.Model_Landmark2_Output_img.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Model_Landmark2_calculator.Model_Landmark2_Calculator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Model_Landmark2_calculator.Model_Landmark2_Calculator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Model_Landmark2_Calculator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Add_second(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Model_Landmark2_calculator.Model_Landmark2_Calculator/Add_second',
            model__landmark__cal__pb2.Model_Landmark2_Input_img.SerializeToString,
            model__landmark__cal__pb2.Model_Landmark2_Output_img.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
