# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model2/model_landmark_cal.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'model2/model_landmark_cal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fmodel2/model_landmark_cal.proto\x12\x19Model_Landmark_calculator\"8\n\x18Model_Landmark_Input_img\x12\x1c\n\x14model_landmark_idata\x18\x01 \x01(\x0c\"9\n\x19Model_Landmark_Output_img\x12\x1c\n\x14model_landmark_odata\x18\x01 \x01(\t2\x8d\x01\n\x19Model_Landmark_Calculator\x12p\n\x03\x41\x64\x64\x12\x33.Model_Landmark_calculator.Model_Landmark_Input_img\x1a\x34.Model_Landmark_calculator.Model_Landmark_Output_imgb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model2.model_landmark_cal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODEL_LANDMARK_INPUT_IMG']._serialized_start=62
  _globals['_MODEL_LANDMARK_INPUT_IMG']._serialized_end=118
  _globals['_MODEL_LANDMARK_OUTPUT_IMG']._serialized_start=120
  _globals['_MODEL_LANDMARK_OUTPUT_IMG']._serialized_end=177
  _globals['_MODEL_LANDMARK_CALCULATOR']._serialized_start=180
  _globals['_MODEL_LANDMARK_CALCULATOR']._serialized_end=321
# @@protoc_insertion_point(module_scope)
